#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT

name: NanoPi Build 24.10 lite

on:
#  release:
#    types: published
  workflow_dispatch:
    inputs:
      openwrt_branch:
        description: 'OpenWrt Branch to build'     
        required: true
        default: '24.10'
        type: choice
        options:
        - '24.10'
      model_R4S:
        description: 'Build R4S'
        type: boolean
        default: true
      #rootfs_size:
        #description: 'RootFS Size'
        #required: true
        #default: '1024MB'
        #type: choice
        #options:
        #- '100MB'
        #- '1024MB'
      build_full:
        description: 'Build full seed'
        type: boolean
        default: true
jobs:
  init:
    #runs-on: ubuntu-22.04
    runs-on: self-hosted
    if: github.event.repository.owner.id == github.event.sender.id

    # Map a step output to a job output
    outputs:
      build_string: ${{ steps.gen_build_string.outputs.build_string }}
      release_tag: ${{ steps.gen_release_tag.outputs.release_tag }}
      matrix: ${{ steps.build_matrix.outputs.matrix }}
    steps:
    - id: gen_build_string
      run: echo "build_string=$(date +%Y.%m.%d)" >> $GITHUB_OUTPUT
    - id: gen_release_tag
      run: echo "release_tag=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
    - id: build_matrix
      run: |
          model_R4S="${{ fromJSON('["", "R4S"]')[github.event.inputs.model_R4S == 'true'] }}"
          model_R2S="${{ fromJSON('["", "R2S"]')[github.event.inputs.model_R2S == 'true'] }}"
          model_R2C="${{ fromJSON('["", "R2C"]')[github.event.inputs.model_R2C == 'true'] }}"
          models="$model_R4S $model_R2S $model_R2C"
          modelsJson=$(echo -n "$models" | jq -R -s -c 'split(" ") | map(select(length>0))')
          matrix="{\"nanopi_model\":$modelsJson}"
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
  
  build:
    needs: init
    strategy:
      matrix: ${{ fromJson(needs.init.outputs.matrix) }}
    
    #runs-on: ubuntu-22.04
    runs-on: self-hosted
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

    - name: Checkout repository
      uses: actions/checkout@main
    
    - name: Free space
      if: runner.environment == 'github-hosted' # for GitHub hosted runners and 'self-hosted'
      run: ./workflow-scripts/free_disk_space.sh

    - name: Setup Linux Requirements
      if: runner.environment == 'github-hosted' # for GitHub hosted runners and 'self-hosted'
      uses: ./.github/actions/setup-devenv

    - name: Set GITHUB_ENV
      run: |
        echo "TZ=America/New_York" >>$GITHUB_ENV
        echo "BUILD_STRING=${{ needs.init.outputs.build_string }}" >> $GITHUB_ENV
        echo "RELTAG=${{ needs.init.outputs.release_tag }}" >> $GITHUB_ENV
        echo "OPENWRT_BRANCH=${{ github.event.inputs.openwrt_branch }}" >> $GITHUB_ENV
        echo "NANOPI_MODEL=${{ matrix.nanopi_model }}" >> $GITHUB_ENV
        echo "BUILD_MINI=${{ github.event.inputs.build_mini }}" >> $GITHUB_ENV
        echo "BUILD_FULL=${{ github.event.inputs.build_full }}" >> $GITHUB_ENV
        #echo "ROOTFS_SIZE=${{ github.event.inputs.rootfs_size }}" >> $GITHUB_ENV

    - name: Show GITHUB_ENV
      run: echo $GITHUB_ENV
    
    - name: Dump github context
      run: echo "$GITHUB_CONTEXT"
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    
    - name: Load NK seed (full, 1024mb roots)
      if: github.event.inputs.build_full == 'true'
      run: |
        echo "ROOTFS_SIZE=1024" >> $GITHUB_ENV
        ./openwrt-$OPENWRT_BRANCH/steps/06-create_config_from_seed.sh $NANOPI_MODEL full $ROOTFS_SIZE

    - name: Compile OpenWRT (full, 1024mb roots)
      id: compileopenwrtfull
      if: github.event.inputs.build_full == 'true'
      continue-on-error: true
      run: |
        cd build/openwrt
        let make_process=$(nproc)+1
        make -j${make_process} || make -j${make_process}
    
    - name: If compile openwrt Error
      if: github.event.inputs.build_full == 'true' && steps.compileopenwrtfull.outcome == 'failure'
      run: |
        cat build/openwrt/.config
        echo '================================================================'
        cd build/openwrt && make -j1 V=s
    
    - name: Organize files (full, 1024mb roots)
      id: organizefull
      if: github.event.inputs.build_full == 'true'
      run: ./openwrt-$OPENWRT_BRANCH/steps/organize_files.sh $NANOPI_MODEL full $OPENWRT_BRANCH $RELTAG $ROOTFS_SIZE

    - name: Load NK seed (full, 100mb roots)
      if: github.event.inputs.build_full == 'true'
      run: |
        echo "ROOTFS_SIZE=100" >> $GITHUB_ENV
        ./openwrt-$OPENWRT_BRANCH/steps/06-create_config_from_seed.sh $NANOPI_MODEL full $ROOTFS_SIZE

    - name: Compile OpenWRT (full, 100mb roots)
      id: compileopenwrtfull-100
      if: github.event.inputs.build_full == 'true'
      continue-on-error: true
      run: |
        cd build/openwrt
        let make_process=$(nproc)+1
        make -j${make_process} || make -j${make_process}
    
    - name: If compile openwrt Error
      if: github.event.inputs.build_full == 'true' && steps.compileopenwrtfull.outcome == 'failure'
      run: |
        cat build/openwrt/.config
        echo '================================================================'
        cd build/openwrt && make -j1 V=s
    
    - name: Organize files (full, 100mb roots)
      id: organizefull-100
      if: github.event.inputs.build_full == 'true'
      run: ./openwrt-$OPENWRT_BRANCH/steps/organize_files.sh $NANOPI_MODEL full $OPENWRT_BRANCH $RELTAG $ROOTFS_SIZE

    - name: Create release
      id: create_release
      uses: ncipollo/release-action@v1.11.1
      if: ${{ !cancelled() }}
      with:
        name: Vanilla OpenWrt ${{ env.OPENWRT_BRANCH }} ${{ env.BUILD_STRING }}
        allowUpdates: true
        tag: Vanilla-OpenWrtNK-${{ env.ROOTFS_SIZE }}-${{ env.OPENWRT_BRANCH }}-${{ env.RELTAG }}
        commit: Vanilla
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        bodyFile: "openwrt-${{ env.OPENWRT_BRANCH }}/release-info.md"
        artifacts: ./artifact/*.img.gz, ./artifact/*.bom.cdx.json, ./artifact/*.manifest
